name: Cache Experiment
on:
  workflow_dispatch:

jobs:
  Cache:
    runs-on: ubuntu-latest

    steps:
    - uses: h0x0er/harden-runner@issue173
    - run: echo "sampel text file" > /home/runner/sample.txt
    - run: cat /home/runner/sample.txt
